"""Pydantic schemas for question data."""

from typing import List, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field


class QuestionCreate(BaseModel):
    """Schema for creating a question."""

    model_config = ConfigDict(str_strip_whitespace=True)

    subject_id: int
    unit_id: int
    bloom_level_id: int
    board_id: Optional[int] = None
    academic_year_id: Optional[int] = None
    class_id: Optional[int] = None
    topic_id: Optional[int] = None
    question_text: str = Field(min_length=1, max_length=2000)
    question_type: Optional[str] = "Short Answer"
    marks: int = Field(default=1, ge=1)
    difficulty: Literal["easy", "medium", "hard"] = "medium"
    answer: Optional[str] = None
    explanation: Optional[str] = None
    source_type: Optional[str] = "teacher"
    status: Optional[str] = "approved"


class QuestionUpdate(BaseModel):
    """Schema for updating a question."""

    subject_id: Optional[int] = None
    unit_id: Optional[int] = None
    bloom_level_id: Optional[int] = None
    board_id: Optional[int] = None
    academic_year_id: Optional[int] = None
    class_id: Optional[int] = None
    topic_id: Optional[int] = None
    question_text: Optional[str] = Field(default=None, min_length=1, max_length=2000)
    question_type: Optional[str] = None
    marks: Optional[int] = Field(default=None, ge=1)
    difficulty: Optional[Literal["easy", "medium", "hard"]] = None
    answer: Optional[str] = None
    explanation: Optional[str] = None
    source_type: Optional[str] = None
    status: Optional[str] = None


class QuestionResponse(BaseModel):
    """Schema for returning question data."""

    id: int
    subject_id: int
    unit_id: int
    bloom_level_id: int
    board_id: Optional[int] = None
    academic_year_id: Optional[int] = None
    class_id: Optional[int] = None
    topic_id: Optional[int] = None
    question_text: str
    question_type: Optional[str] = "Short Answer"
    marks: int
    difficulty: str
    answer: Optional[str] = None
    explanation: Optional[str] = None
    source_type: Optional[str] = "teacher"
    status: Optional[str] = "approved"

    model_config = ConfigDict(from_attributes=True)



class BulkQuestionUploadItem(BaseModel):
    """Schema for a single question in bulk upload."""

    subject_name: Optional[str] = None
    subject_id: Optional[int] = None
    unit_name: Optional[str] = None
    unit_id: Optional[int] = None
    bloom_level: Optional[str] = None
    bloom_level_id: Optional[int] = None
    question_text: str = Field(min_length=1)
    question_type: Optional[str] = "Short Answer"
    marks: int = Field(default=1, ge=1)
    difficulty: Optional[str] = "medium"
    answer: Optional[str] = None
    explanation: Optional[str] = None


class BulkUploadRowError(BaseModel):
    row_index: int
    question_text: str
    error: str


class BulkQuestionUploadResponse(BaseModel):
    """Schema for bulk question upload result summary."""

    total_submitted: int
    successful_count: int
    failed_count: int
    created_questions: List[QuestionResponse]
    errors: List[BulkUploadRowError]


class AIGenerateRequest(BaseModel):
    """Schema for requesting AI question generation."""

    subject_id: int
    unit_id: int
    bloom_level_id: int
    difficulty: Literal["easy", "medium", "hard"] = "medium"
    marks: int = Field(default=1, ge=1)
    count: int = Field(default=1, ge=1, le=10)
    textbook_context: Optional[str] = None


class AIGeneratedQuestion(BaseModel):
    """Schema for a single question generated by AI."""

    question_text: str
    difficulty: str
    marks: int


class AIGenerateResponse(BaseModel):
    """Schema for returning AI generated questions."""

    questions: list[AIGeneratedQuestion]

